[tool.poetry]
name = "data-to-text-hierarchical"
version = "0.1.0"
description = ""
authors = ["Prakhar Agnihotri <rounak316@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
